### ISSUE TITLE
Types are broken

### ISSUE THREAD

**Issue by 0xMALVEE** [momentohq/momento-node-ioredis-client#18]
![image](https://github.com/momentohq/momento-node-ioredis-client/assets/35369563/a422c401-0118-4baa-98f2-bc82983e5b66)

```js
 const Redis = new MomentoRedisAdapter(
        new CacheClient({
          configuration: Configurations.Laptop.v1(),
          credentialProvider: CredentialProvider.fromEnvironmentVariable({
            environmentVariableName: "MOMENTO_AUTH_TOKEN",
          }),
          defaultTtlSeconds: 3600,
        }),
        "myMomentoCache",
      );
```

**Comment by cprice404** [comment]
hi @0xMALVEE ! Thanks for the bug report.

This error message looks like you might have 2 different versions of the momento nodejs SDK installed; perhaps you have one listed directly in your `package.json` file, and one that you are getting transitively from `momento-node-ioredis-client`?

Can you share your package.json file, or the dependencies part of it? I believe this problem should be resolved if you ensure that you've installed the same version of the momento nodejs sdk that the ioredis client depends on.

We will also try to make a few changes to make this setup experience work a little better, but please let us know if that resolves it!

**Comment by 0xMALVEE** [comment]
![image](https://github.com/momentohq/momento-node-ioredis-client/assets/35369563/118258e7-ab6a-4031-87e7-47a99bcdff6f)
@cprice404

**Comment by cprice404** [comment]
So, node-ioredis-client currently has a strict dependency on @gomomento/sdk v1.77.0:

https://github.com/momentohq/momento-node-ioredis-client/blob/e6999d0f17cff273ec513bc05d8f27108abad6a1/package.json#L23

Having two different versions of the `sdk` module will cause the errors you are sharing. You can try changing the dependency in the package.json file to `1.77.0` instead, I believe that will fix it.

In the meantime we will also look into relaxing this dependency constraint to prevent this issue, and maybe we can also re-export the necessary things from the `sdk` package so that you don't need to express an explicit dependency on it.

Let me know if pinning to 1.77.0 works for now though!
